"""Markdown report serializer tests."""

from utils.markdown_export import session_to_markdown
from utils.models import (
    TestCase, TestSession, GherkinStep, AnalysisReport, ExecutionMetrics,
    Action, Locator,
)


def make_session():
    return TestSession(
        session_id="abc123def",
        feature="Password reset flow",
        state="EXECUTED",
        timestamp=1700000000.0,
        test_cases=[
            TestCase(
                id="TC001", type="Positive", description="happy reset",
                tags=["@smoke", "@happy"],
                scenario="Successful reset", expected="Dashboard visible",
                steps=["Given on /login"],
                gherkin_steps=[
                    GherkinStep(keyword="Given", text="user is on /login"),
                    GherkinStep(keyword="Then", text="dashboard visible"),
                ],
                action_plan=[
                    Action(op="goto", url="https://x.com/login"),
                    Action(op="click", locator=Locator(by="css", value="button[type=submit]")),
                ],
                status="Pass", selenium_action="",
            ),
            TestCase(
                id="TC002", type="Negative", description="bad creds",
                expected="Error shown", steps=["s"], selenium_action="",
                status="Fail", error="AssertionError: 'Welcome' not in 'Forbidden'",
                bug_insight="Likely a backend authz regression.",
                screenshot="data/screenshots/abc123/failure_TC002.png",
            ),
        ],
        report=AnalysisReport(
            metrics=ExecutionMetrics(total=2, passed=1, failed=1),
            executive_summary="1/2 passed. Auth regression suspected.",
            test_cases=[],
        ),
    )


def test_session_markdown_contains_feature_and_metrics():
    md = session_to_markdown(make_session())
    assert "# Password reset flow" in md
    assert "**Total:** 2" in md
    assert "**Pass:** 1" in md
    assert "**Pass rate:** 50.0%" in md


def test_session_markdown_renders_failures_and_passes():
    md = session_to_markdown(make_session())
    assert "## Failures (1)" in md
    assert "## Passes (1)" in md
    assert "TC001" in md and "TC002" in md
    assert "🤖 **AI insight:** Likely" in md
    assert "AssertionError" in md


def test_session_markdown_renders_gherkin_block():
    md = session_to_markdown(make_session())
    assert "```gherkin" in md
    assert "Scenario: Successful reset" in md
    assert "Given user is on /login" in md


def test_session_markdown_handles_no_report():
    s = TestSession(
        session_id="s", feature="x", timestamp=1.0,
        test_cases=[TestCase(
            id="T", type="Positive", description="d", steps=["s"],
            selenium_action="", expected="ok", status="Pass",
        )],
    )
    md = session_to_markdown(s)
    assert "Generated by AbhiMate." in md


def test_session_markdown_marks_known_issue():
    s = TestSession(
        session_id="s", feature="x", timestamp=1.0,
        test_cases=[TestCase(
            id="T", type="Positive", description="d", steps=["s"],
            selenium_action="", expected="ok", status="Fail",
            error="boom", known_issue=True,
        )],
    )
    md = session_to_markdown(s)
    assert "Known issue:** yes" in md
