"""Smoke tests for /api/runs/diff (now login-gated)."""

import uuid

import pytest


@pytest.fixture
def app_client(auth_client, app_module):
    """Provides an authenticated test client + the app module + helpers."""
    client, user_id = auth_client
    return client, app_module, user_id


def _make_session(app_module, session_id, cases, user_id=None):
    from utils.models import TestSession, TestCase
    s = TestSession(
        session_id=session_id,
        user_id=user_id,
        feature=f"feat-{session_id}",
        state="EXECUTED",
        timestamp=1.0,
        test_cases=[TestCase(**c) for c in cases],
    )
    app_module.memory_agent.save_session(s, user_id=user_id)


def test_diff_requires_both_ids(app_client):
    client, _, _ = app_client
    r = client.get("/api/runs/diff?a=only")
    assert r.status_code == 400


def test_diff_404_when_session_missing(app_client):
    client, _, _ = app_client
    r = client.get("/api/runs/diff?a=nope1&b=nope2")
    assert r.status_code == 404


def test_diff_requires_auth(anonymous_client):
    r = anonymous_client.get("/api/runs/diff?a=x&b=y")
    assert r.status_code == 401


def test_diff_classifies_fixed_regressed_stable(app_client):
    client, app_module, uid = app_client
    sid_a = f"A-{uuid.uuid4().hex[:6]}"
    sid_b = f"B-{uuid.uuid4().hex[:6]}"
    _make_session(app_module, sid_a, [
        {"id": "T1", "type": "Positive", "description": "first", "steps": ["s"],
         "selenium_action": "", "expected": "x", "status": "Fail", "error": "x"},
        {"id": "T2", "type": "Positive", "description": "second", "steps": ["s"],
         "selenium_action": "", "expected": "x", "status": "Pass"},
        {"id": "T3", "type": "Positive", "description": "third", "steps": ["s"],
         "selenium_action": "", "expected": "x", "status": "Pass"},
    ], user_id=uid)
    _make_session(app_module, sid_b, [
        {"id": "T1", "type": "Positive", "description": "first", "steps": ["s"],
         "selenium_action": "", "expected": "x", "status": "Pass"},
        {"id": "T2", "type": "Positive", "description": "second", "steps": ["s"],
         "selenium_action": "", "expected": "x", "status": "Fail", "error": "y"},
        {"id": "T3", "type": "Positive", "description": "third", "steps": ["s"],
         "selenium_action": "", "expected": "x", "status": "Pass"},
        {"id": "T4", "type": "Edge", "description": "fourth", "steps": ["s"],
         "selenium_action": "", "expected": "x", "status": "Fail", "error": "z"},
    ], user_id=uid)

    r = client.get(f"/api/runs/diff?a={sid_a}&b={sid_b}")
    assert r.status_code == 200
    data = r.get_json()
    rows = {row["id"]: row["delta"] for row in data["rows"]}
    assert rows["T1"] == "fixed"
    assert rows["T2"] == "regressed"
    assert rows["T3"] == "stable"
    assert rows["T4"] == "new"


def test_export_markdown_endpoint(app_client):
    client, app_module, uid = app_client
    sid = f"EXP-{uuid.uuid4().hex[:6]}"
    _make_session(app_module, sid, [
        {"id": "X", "type": "Positive", "description": "happy", "steps": ["s"],
         "selenium_action": "", "expected": "ok", "status": "Pass"},
    ], user_id=uid)
    r = client.get(f"/api/sessions/{sid}/export.md")
    assert r.status_code == 200
    assert "text/markdown" in r.headers.get("Content-Type", "")
    body = r.data.decode("utf-8")
    assert f"# feat-{sid}" in body
    assert "Generated by AbhiMate." in body
