"""Render a TestSession as a shareable Markdown report.

Used by /api/sessions/<sid>/export.md so users can paste run results into PRs,
Slack, or JIRA without screenshotting.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, List

if TYPE_CHECKING:
    from utils.models import TestSession, TestCase


_STATUS_BADGE = {
    "Pass": "✅ Pass",
    "Fail": "❌ Fail",
    "Skipped": "⏭️ Skipped",
    "Blocked": "🚧 Blocked",
    "Flaky": "⚠️ Flaky",
    "Un-Run": "⏳ Un-Run",
}


def _badge(status: str) -> str:
    return _STATUS_BADGE.get(status or "Un-Run", status or "Un-Run")


def _format_case(tc: "TestCase") -> List[str]:
    out: List[str] = []
    out.append(f"### {tc.id} — {tc.description}")
    if tc.tags:
        out.append("`" + "` `".join(tc.tags) + "`")
    out.append("")
    out.append(f"- **Type:** {tc.type}")
    out.append(f"- **Status:** {_badge(tc.status or 'Un-Run')}")
    if tc.expected:
        out.append(f"- **Expected:** {tc.expected}")
    if tc.known_issue:
        out.append("- **Known issue:** yes (excluded from health metrics)")

    if tc.gherkin_steps:
        out.append("")
        out.append("**Scenario**")
        out.append("```gherkin")
        if tc.scenario:
            out.append(f"Scenario: {tc.scenario}")
        for s in tc.gherkin_steps:
            out.append(f"  {s.keyword} {s.text}")
        out.append("```")
    elif tc.steps:
        out.append("")
        out.append("**Steps**")
        for s in tc.steps:
            out.append(f"  - {s}")

    if tc.action_plan:
        out.append("")
        out.append(f"<details><summary>Action plan ({len(tc.action_plan)} ops)</summary>")
        out.append("")
        for a in tc.action_plan:
            loc = ""
            if a.locator:
                loc = f" `{a.locator.by}={a.locator.value}`"
            out.append(f"- `{a.op}`{loc}" + (f" → {a.value!r}" if a.value else ""))
        out.append("</details>")

    if tc.error:
        out.append("")
        out.append("**Error**")
        out.append("```")
        out.append(tc.error)
        out.append("```")
    if tc.bug_insight:
        out.append("")
        out.append(f"> 🤖 **AI insight:** {tc.bug_insight}")
    if tc.screenshot:
        out.append("")
        out.append(f"![Failure screenshot for {tc.id}](/{tc.screenshot})")

    out.append("")
    out.append("---")
    out.append("")
    return out


def session_to_markdown(session: "TestSession") -> str:
    lines: List[str] = []
    lines.append(f"# {session.feature or 'AbhiMate session'} — {session.session_id[:8]}")
    lines.append("")
    lines.append(f"- **State:** {session.state}")
    lines.append(f"- **Timestamp:** {session.timestamp}")

    metrics = session.report.metrics if session.report else None
    if metrics is not None:
        passes = metrics.passed or 0
        total = metrics.total or 0
        rate = round((passes / total) * 100, 1) if total else 0
        lines.append(f"- **Total:** {total}    **Pass:** {passes}    **Fail:** {metrics.failed}    "
                     f"**Skipped:** {metrics.skipped}    **Pass rate:** {rate}%")

    if session.report and session.report.executive_summary:
        lines.append("")
        lines.append("## Executive summary")
        lines.append("")
        lines.append("> " + session.report.executive_summary.replace("\n", "\n> "))

    failed = [tc for tc in session.test_cases if tc.status == "Fail"]
    if failed:
        lines.append("")
        lines.append(f"## Failures ({len(failed)})")
        lines.append("")
        for tc in failed:
            lines.extend(_format_case(tc))

    passes = [tc for tc in session.test_cases if tc.status == "Pass"]
    if passes:
        lines.append(f"## Passes ({len(passes)})")
        lines.append("")
        for tc in passes:
            lines.extend(_format_case(tc))

    other = [tc for tc in session.test_cases if tc.status not in {"Pass", "Fail"}]
    if other:
        lines.append(f"## Other ({len(other)})")
        lines.append("")
        for tc in other:
            lines.extend(_format_case(tc))

    lines.append("")
    lines.append("---")
    lines.append("Generated by AbhiMate.")
    return "\n".join(lines)
